#cd /home/hit_alan/zhoufandi/somefilebetweenlinuxandwindows/androguard-2.0
#sh androsim.sh
# the $1 means the dir of the analyzer the $2 means the detail dir generated by the time 
cd $1/dex2jar-2.0
sh birthmark.sh $2


