#$1 is the dir of the analyzer
#$2 is the type of detail dir which is generated by the analyzer by time
cd $1
sh ./copyfilev2.sh $2
cd $1/clientapk/$2
sh ./getDexv2.sh
cd $1/channelapk/$2
sh ./getDexv2.sh
