#$1 is the dir of the analyzer
#$2 is the type of info.sh which is help us whether we need the secondclientapk
#$3 is the type of detail dir which is generated by the analyzer by time
cd $1
if [ "$2" = "1" ] 
 then
 ./getPackageAndVersion.sh secondclientapk/$3
else
 ./getPackageAndVersion.sh clientapk/$3
fi
 ./getPackageAndVersion.sh channelapk/$3
sh ./copyfile.sh $2 $3
if [ "$2" = "1" ]
 then 
 cd $1/secondclientapk/$3
 sh ./getDexHash.sh
else
cd $1/clientapk/$3
sh ./getDexHash.sh
fi
cd $1/channelapk/$3
sh ./getDexHash.sh
