#$1 means the analyzer address
#$2 means the detail floder name generated by time
#$3 means the type of the bad apk
#$4 means the packagename of the apk
#$5 means the subtaskId which can determine the apk
  newAPKname=$5".apk"
if [ "$3" = "0" ];then
  if [ -d ~/badApp/repackageapk/$4 ];then
  echo "floder exist"
  else
  mkdir ~/badApp/repackageapk/$4
  fi
  cp $1/$2/channel.apk ~/badApp/repackageapk/$4/$newAPKname
  echo "copy the repackageapk into a new folder"
elif [ "$3" = "1" ];then
  if [ -d ~/badApp/piracy/$4 ];then
  echo "floder exist"
  else
  mkdir ~/badApp/piracy/$4
  fi
  cp $1/$2/channel.apk ~/badApp/piracy/$4/$newAPKname
  echo "copy the piracyapk into a new folder"
else
  if [ -d ~/badApp/fish/$4 ];then
  echo "floder exist"
  else
  mkdir ~/badApp/fish/$4
  fi
  cp $1/$2/channel.apk ~/badApp/fish/$4/$newAPKname
  echo "copy the fish apk into a new folder"
fi
